In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.utils.data as data
import torch.nn.functional as F
import torchaudio
from comet_ml import Experiment
import os
import json
from pprint import pprint

# Dataset Downloading

In [2]:
"""
'SpeechCommands'        - full dataset          (51088 train, 6798 valid, 6835 test)
'SpeechCommandsBinary'  - only 'yes' and 'go'   ( 3721 train,  521 valid,  507 test)
"""
DATASET_FOLDER='SpeechCommandsBinary'

In [3]:
def download_data(dataset_folder, download=False):
    if not os.path.isdir("./data"):
        os.makedirs("./data")

    train_dataset = torchaudio.datasets.SPEECHCOMMANDS(root='./data', folder_in_archive=dataset_folder, url='speech_commands_v0.01', download=download, subset='training')
    valid_dataset = torchaudio.datasets.SPEECHCOMMANDS(root='./data', folder_in_archive=dataset_folder, url='speech_commands_v0.01', download=download, subset='validation')
    test_dataset = torchaudio.datasets.SPEECHCOMMANDS(root='./data', folder_in_archive=dataset_folder, url='speech_commands_v0.01', download=download, subset='testing')
    return train_dataset, valid_dataset, test_dataset

In [4]:
train_dataset, valid_dataset, test_dataset = download_data(DATASET_FOLDER)
print(len(train_dataset), len(valid_dataset), len(test_dataset), )

3721 521 507


# Data Processing

In [5]:
char_map_str = """
<BLANK> 0
a 1
b 2
c 3
d 4
e 5
f 6
g 7
h 8
i 9
j 10
k 11
l 12
m 13
n 14
o 15
p 16
q 17
r 18
s 19
t 20
u 21
v 22
w 23
x 24
y 25
z 26
"""

BLANK_LABEL = None  # to be assigned in TextTranform constructor

class TextTransform:
    """ Maps characters to their indices, and vice versa """
    def __init__(self):
        self.char_map = {}
        self.index_map = {}
        global BLANK_LABEL
        for line in char_map_str.strip().split('\n'):
            ch, index = line.split()
            self.char_map[ch] = int(index)
            self.index_map[int(index)] = ch
            if not BLANK_LABEL and ch == '<BLANK>':
                BLANK_LABEL = int(index)
        self.index_map[BLANK_LABEL] = ' '

    def text_to_int(self, text: list[str]):
        """ Use a character map and convert text to an integer sequence """
        int_sequence = []
        for c in text:
            if c == ' ':
                ind = self.char_map['<BLANK>']
            else:
                ind = self.char_map[c]
            int_sequence.append(ind)
        return int_sequence

    def int_to_text(self, labels: list[int]):
        """ Use a character map and convert integer labels to an text sequence """
        string = []
        for i in labels:
            string.append(self.index_map[i])
        return ''.join(string).replace('<BLANK>', ' ')


# TODO: SpecAugment (masking augmentations)
train_audio_transforms = nn.Sequential(
    torchaudio.transforms.MelSpectrogram(sample_rate=16000, n_mels=128),
    # torchaudio.transforms.FrequencyMasking(freq_mask_param=15),
    # torchaudio.transforms.TimeMasking(time_mask_param=35)
)

valid_audio_transforms = torchaudio.transforms.MelSpectrogram()

text_transform = TextTransform()

/home/pigeon_gcc/anaconda3/envs/asr_project/lib/python3.9/site-packages/torchaudio/functional/functional.py:571: UserWarning: At least one mel filterbank has all zero values. The value for `n_mels` (128) may be set too high. Or, the value for `n_freqs` (201) may be set too low.
  warnings.warn(


In [6]:
print(BLANK_LABEL)

0


In [7]:
# testing the code above
word_start = "yes"
index = text_transform.text_to_int(word_start)
word_recovered = text_transform.int_to_text(index)

print(word_start, "-->", index, "-->", word_recovered)

yes --> [25, 5, 19] --> yes


The function __data_processing()__ will be called in Data Loaders' __collate_fn__.

Data is represented as tuple(wave, sample_rate, utterance (label), speaker id, utterance number)

In [8]:
sample = train_dataset.__getitem__(n=2)
sample

(tensor([[ 0.0015,  0.0014,  0.0002,  ..., -0.0018, -0.0041, -0.0064]]),
 16000,
 'go',
 '00b01445',
 0)

In [9]:
def data_processing(data, data_type="train"):
    spectrograms = []
    labels = []
    input_lengths = []
    label_lengths = []
    for (waveform, _, utterance, _, _) in data:
        if data_type == 'train':
            spec = train_audio_transforms(waveform).squeeze(0).transpose(0, 1)
        else:
            spec = valid_audio_transforms(waveform).squeeze(0).transpose(0, 1)
        spectrograms.append(spec)
        # labels are lists of integer character ids
        label = torch.Tensor(text_transform.text_to_int(utterance.lower()))
        labels.append(label)
        # input_lengths, label_lengths are used in loss function
        input_lengths.append(spec.shape[0]//2)
        label_lengths.append(len(label))

    spectrograms = nn.utils.rnn.pad_sequence(spectrograms, batch_first=True).unsqueeze(1).transpose(2, 3)
    labels = nn.utils.rnn.pad_sequence(labels, batch_first=True)

    return spectrograms, labels, input_lengths, label_lengths

In [10]:
# testing
data_processing((sample,))

(tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00,  ..., 0.0000e+00,
            0.0000e+00, 0.0000e+00],
           [5.6114e-06, 2.3897e-08, 4.6804e-09,  ..., 5.0149e-08,
            1.4150e-07, 5.2350e-04],
           [3.0213e-05, 1.2867e-07, 2.5200e-08,  ..., 2.7001e-07,
            7.6186e-07, 2.8187e-03],
           ...,
           [6.2869e-06, 3.1005e-06, 1.3310e-06,  ..., 4.2932e-06,
            1.1480e-05, 2.2970e-05],
           [2.9710e-06, 1.8165e-07, 2.1055e-07,  ..., 1.9169e-07,
            4.7822e-07, 1.5796e-05],
           [1.5043e-06, 6.5866e-08, 3.1178e-08,  ..., 4.1545e-08,
            3.6824e-08, 1.7976e-05]]]]),
 tensor([[ 7., 15.]]),
 [40],
 [2])

## CER - Character Error Rate

In [11]:
def _levenshtein_distance(ref, hyp):
    """Levenshtein distance is a string metric for measuring the difference
    between two sequences. Informally, the levenshtein disctance is defined as
    the minimum number of single-character edits (substitutions, insertions or
    deletions) required to change one word into the other. We can naturally
    extend the edits to word level when calculate levenshtein disctance for
    two sentences.
    """
    m = len(ref)
    n = len(hyp)

    # special case
    if ref == hyp:
        return 0
    if m == 0:
        return n
    if n == 0:
        return m

    if m < n:
        ref, hyp = hyp, ref
        m, n = n, m

    # use O(min(m, n)) space
    distance = np.zeros((2, n + 1), dtype=np.int32)

    # initialize distance matrix
    for j in range(0,n + 1):
        distance[0][j] = j

    # calculate levenshtein distance
    for i in range(1, m + 1):
        prev_row_idx = (i - 1) % 2
        cur_row_idx = i % 2
        distance[cur_row_idx][0] = i
        for j in range(1, n + 1):
            if ref[i - 1] == hyp[j - 1]:
                distance[cur_row_idx][j] = distance[prev_row_idx][j - 1]
            else:
                s_num = distance[prev_row_idx][j - 1] + 1
                i_num = distance[cur_row_idx][j - 1] + 1
                d_num = distance[prev_row_idx][j] + 1
                distance[cur_row_idx][j] = min(s_num, i_num, d_num)

    return distance[m % 2][n]


def char_errors(reference, hypothesis, ignore_case=False, remove_space=False):
    """Compute the levenshtein distance between reference sequence and
    hypothesis sequence in char-level.
    :param reference: The reference sentence.
    :type reference: basestring
    :param hypothesis: The hypothesis sentence.
    :type hypothesis: basestring
    :param ignore_case: Whether case-sensitive or not.
    :type ignore_case: bool
    :param remove_space: Whether remove internal space characters
    :type remove_space: bool
    :return: Levenshtein distance and length of reference sentence.
    :rtype: list
    """
    if ignore_case == True:
        reference = reference.lower()
        hypothesis = hypothesis.lower()

    join_char = ' '
    if remove_space == True:
        join_char = ''

    reference = join_char.join(filter(None, reference.split(' ')))
    hypothesis = join_char.join(filter(None, hypothesis.split(' ')))

    edit_distance = _levenshtein_distance(reference, hypothesis)
    return float(edit_distance), len(reference)


def cer(reference, hypothesis, ignore_case=False, remove_space=False):
    """Calculate charactor error rate (CER). CER compares reference text and
    hypothesis text in char-level. CER is defined as:
    .. math::
        CER = (Sc + Dc + Ic) / Nc
    where
    .. code-block:: text
        Sc is the number of characters substituted,
        Dc is the number of characters deleted,
        Ic is the number of characters inserted
        Nc is the number of characters in the reference
    We can use levenshtein distance to calculate CER. Chinese input should be
    encoded to unicode. Please draw an attention that the leading and tailing
    space characters will be truncated and multiple consecutive space
    characters in a sentence will be replaced by one space character.
    :param reference: The reference sentence.
    :type reference: basestring
    :param hypothesis: The hypothesis sentence.
    :type hypothesis: basestring
    :param ignore_case: Whether case-sensitive or not.
    :type ignore_case: bool
    :param remove_space: Whether remove internal space characters
    :type remove_space: bool
    :return: Character error rate.
    :rtype: float
    :raises ValueError: If the reference length is zero.
    """
    edit_distance, ref_len = char_errors(reference, hypothesis, ignore_case,
                                         remove_space)

    if ref_len == 0:
        raise ValueError("Length of reference should be greater than 0.")

    cer = float(edit_distance) / ref_len
    return cer

# Building a Model

## NN Architecture

We use Layer Normalization, not Batch Normalization, because BN is hard to use with sequence data, with small batch sizes, and it's hard to paralellize a NN with BN.

This is due to the dependency on batches. Layer Normalization removes this dependency. It computes the normalization based on the layers inside of the batches.

LN briefly: Input values in all neurons in the same layer are normalized for each data sample.
So, all values in neurons of the same layer will have the same mean and variance.

LN is can deal with sequence data, doesn't depend on batch size, and is easily paralellized.
However, LN sometimes performs worse than BN with CNNs.

In [12]:
class CNNLayerNorm(nn.Module):
    """Layer Normalization"""
    
    def __init__(self, n_features):
        super(CNNLayerNorm, self).__init__()
        self.layer_norm = nn.LayerNorm(normalized_shape=n_features)
        """About normalized_shape parameter of nn.LayerNorm:
        If a single integer is used, it is treated as a singleton list, and this module will normalize
        over the last dimension which is expected to be of that specific size.
        """

    def forward(self, x):
        # x (batch, channel, feature, time)
        x = x.transpose(2, 3).contiguous() # (batch, channel, time, feature)
        x = self.layer_norm(x)
        return x.transpose(2, 3).contiguous() # (batch, channel, feature, time) 

class ResidualCNN(nn.Module):
    """ Residual CNN inspired by https://arxiv.org/pdf/1603.05027.pdf
        except with layer norm instead of batch norm """
    
    def __init__(self, in_channels, out_channels, kernel, stride, dropout, n_features):
        super(ResidualCNN, self).__init__()

        self.layer_norm1 = CNNLayerNorm(n_features)
        self.dropout1 = nn.Dropout(dropout)
        self.cnn1 = nn.Conv2d(in_channels, out_channels, kernel, stride, padding=kernel//2)

        self.layer_norm2 = CNNLayerNorm(n_features)
        self.dropout2 = nn.Dropout(dropout)
        self.cnn2 = nn.Conv2d(out_channels, out_channels, kernel, stride, padding=kernel//2)

    def forward(self, x):
        residual = x  # (batch, channel, feature, time)
        out = self.layer_norm1(x)
        out = F.gelu(out)
        out = self.dropout1(out)
        out = self.cnn1(out)
        out = self.layer_norm2(out)
        out = F.gelu(out)
        out = self.dropout2(out)
        out = self.cnn2(out)
        out += residual
        return out # (batch, channel, feature, time)
        
class BidirectionalGRU(nn.Module):

    def __init__(self, rnn_dim, hidden_size, dropout, batch_first):
        super(BidirectionalGRU, self).__init__()

        self.layer_norm = nn.LayerNorm(rnn_dim)
        self.BiGRU = nn.GRU(
            input_size=rnn_dim, hidden_size=hidden_size,
            num_layers=1, batch_first=batch_first, bidirectional=True)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = self.layer_norm(x)
        out = F.gelu(out)
        out, _ = self.BiGRU(out)
        out = self.dropout(out)
        return out


class SpeechRecognitionModel(nn.Module):
    """Speech Recognition Model Inspired by DeepSpeech 2"""

    def __init__(self, n_cnn_layers, n_rnn_layers, rnn_dim, n_class, n_features, stride=2, dropout=0.1):
        super(SpeechRecognitionModel, self).__init__()
        n_features = n_features // 2

        # TODO: чзх этот conv слой тут забыл?
        self.cnn = nn.Conv2d(1, 32, 3, stride=stride, padding=3 // 2)  # cnn for extracting heirachal features

        # n residual cnn layers with filter size of 32
        self.rescnn_layers = nn.Sequential(*[
            ResidualCNN(32, 32, kernel=3, stride=1, dropout=dropout, n_features=n_features) 
            for _ in range(n_cnn_layers)
        ])
        self.fully_connected = nn.Linear(n_features*32, rnn_dim)
        """TODO: как я понял, у нас число фичей rnn_dim берётся одиночное для первой GRU, т.к. к ней не перетекает скрытое состояние.
        Каждая следующая GRU получает 2*rnn_dim фичей, т.к. к самим фичам конкатенируется скрытое состояние такой же размерности (hidden_size=rnn_dim)
        """
        self.birnn_layers = nn.Sequential(*[
            BidirectionalGRU(rnn_dim=rnn_dim if i==0 else rnn_dim*2,
                             hidden_size=rnn_dim, dropout=dropout, batch_first=i==0)
            for i in range(n_rnn_layers)
        ])
        self.classifier = nn.Sequential(
            nn.Linear(rnn_dim*2, rnn_dim),  # birnn returns rnn_dim*2
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(rnn_dim, n_class)
        )

    def forward(self, x):
        x = self.cnn(x)
        x = self.rescnn_layers(x)
        sizes = x.size()
        x = x.view(sizes[0], sizes[1] * sizes[2], sizes[3])  # (batch, feature, time)
        x = x.transpose(1, 2) # (batch, time, feature)
        x = self.fully_connected(x)
        x = self.birnn_layers(x)
        x = self.classifier(x)
        return x

# Decoder

In [13]:
def GreedyDecoder(output, labels, label_lengths, blank_label=BLANK_LABEL, collapse_repeated=True):
    arg_maxes = torch.argmax(output, dim=2)
    decodes = []
    targets = []
    for i, args in enumerate(arg_maxes):
        decode = []
        targets.append(text_transform.int_to_text(labels[i][:label_lengths[i]].tolist()))
        for j, index in enumerate(args):
            if index != blank_label:
                if collapse_repeated and j != 0 and index == args[j -1]:
                    continue
                decode.append(index.item())
        decodes.append(text_transform.int_to_text(decode))
    return decodes, targets

# Training

In [14]:
def get_device():
    use_cuda = torch.cuda.is_available()
    torch.manual_seed(7)
    device = torch.device("cuda" if use_cuda else "cpu")
    return device, use_cuda

In [15]:
class IterMeter(object):
    """Keeps track of total iterations. Used for Comet.ml"""
    def __init__(self):
        self.val = 0

    def step(self):
        self.val += 1

    def get(self):
        return self.val


def train(model, device, train_loader, criterion, optimizer, scheduler, epoch, iter_meter, experiment):
    model.train()
    data_len = len(train_loader.dataset)
    with experiment.train():
        for batch_idx, _data in enumerate(train_loader):
            spectrograms, labels, input_lengths, label_lengths = _data 
            spectrograms, labels = spectrograms.to(device), labels.to(device)

            optimizer.zero_grad()

            output = model(spectrograms)  # (batch, time, n_class)
            output = F.log_softmax(output, dim=2)
            output = output.transpose(0, 1) # (time, batch, n_class)

            loss = criterion(output, labels, input_lengths, label_lengths)
            loss.backward()

            experiment.log_metric('loss', loss.item(), step=iter_meter.get())
            experiment.log_metric('learning_rate', scheduler.get_last_lr(), step=iter_meter.get())

            optimizer.step()
            #scheduler.step()   # scheduler step for oncecell scheduler
            iter_meter.step()

            if batch_idx % 100 == 0 or batch_idx == data_len:
                print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                    epoch, batch_idx * len(spectrograms), data_len,
                    100. * batch_idx / len(train_loader), loss.item()))


def test(model, device, test_loader, criterion, epoch, iter_meter, experiment):
    print('\nEvaluating…')
    model.eval()
    test_loss = 0
    test_cer = []
    with experiment.test():
        with torch.no_grad():
            for I, _data in enumerate(test_loader):
                spectrograms, labels, input_lengths, label_lengths = _data 
                spectrograms, labels = spectrograms.to(device), labels.to(device)

                output = model(spectrograms)  # (batch, time, n_class)
                output = F.log_softmax(output, dim=2)
                output = output.transpose(0, 1) # (time, batch, n_class)

                loss = criterion(output, labels, input_lengths, label_lengths)
                test_loss += loss.item() / len(test_loader)

                decoded_preds, decoded_targets = GreedyDecoder(output.transpose(0, 1), labels, label_lengths)
                for j in range(len(decoded_preds)):
                    test_cer.append(cer(decoded_targets[j], decoded_preds[j]))

    avg_cer = sum(test_cer)/len(test_cer)
    experiment.log_metric('test_loss', test_loss, step=iter_meter.get())
    experiment.log_metric('cer', avg_cer, step=iter_meter.get())

    print('Test set: Average loss: {:.4f}, Average CER: {:4f}\n'.format(test_loss, avg_cer))


def train_test(hparams, experiment=Experiment(api_key='dummy_key', disabled=True)):

    experiment.log_parameters(hparams)

    train_dataset, valid_dataset, test_dataset = download_data(DATASET_FOLDER)

    device, use_cuda = get_device()

    kwargs = {'num_workers': 1, 'pin_memory': True} if use_cuda else {}
    train_loader = data.DataLoader(dataset=train_dataset,
                                batch_size=hparams['batch_size'],
                                shuffle=True,
                                collate_fn=lambda x: data_processing(x, 'train'),
                                **kwargs)
    test_loader = data.DataLoader(dataset=test_dataset,
                                batch_size=hparams['batch_size'],
                                shuffle=False,
                                collate_fn=lambda x: data_processing(x, 'test'),
                                **kwargs)

    model = SpeechRecognitionModel(
        hparams['n_cnn_layers'], hparams['n_rnn_layers'], hparams['rnn_dim'],
        hparams['n_class'], hparams['n_feats'], hparams['stride'], hparams['dropout']
        ).to(device)

    print(model)
    print('Num Model Parameters', sum([param.nelement() for param in model.parameters()]))

    #optimizer = optim.AdamW(model.parameters(), hparams['learning_rate'])
    optimizer = optim.Adam(model.parameters(), hparams['learning_rate'])
    criterion = nn.CTCLoss(blank=BLANK_LABEL).to(device)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=hparams['scheduler_step_size'], gamma=hparams['scheduler_gamma'], verbose=True)
    # scheduler = optim.lr_scheduler.OneCycleLR(optimizer, max_lr=hparams['learning_rate'], 
    #                                         steps_per_epoch=int(len(train_loader)),
    #                                         epochs=hparams['epochs'],
    #                                         anneal_strategy='linear')

    iter_meter = IterMeter()
    for epoch in range(1, hparams['epochs'] + 1):
        train(model, device, train_loader, criterion, optimizer, scheduler, epoch, iter_meter, experiment)
        test(model, device, test_loader, criterion, epoch, iter_meter, experiment)
        scheduler.step()   # scheduler step for stepLR scheduler

    return model

COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.


Experiments are monitored using Comet.ml:

In [ ]:
comet_api_key = "KddYvSKPDO9U8K1lZUIUCgHjT"
project_name = "speech-recognition"
experiment_name = "asr-scheduler:steplr-data:binary"

# comet_api_key = ""
# project_name = "speechrecognition"
# experiment_name = "speechrecognition-colab"

if comet_api_key:
    experiment = Experiment(api_key=comet_api_key, project_name=project_name, parse_args=False)
    experiment.set_name(experiment_name)
    experiment.display()
else:
    experiment = Experiment(api_key='dummy_key', disabled=True)

Run the training loop:

In [ ]:
hparams = {
    "n_cnn_layers": 3,
    "n_rnn_layers": 3,
    "rnn_dim": 256,
    "n_class": len(text_transform.char_map),
    "n_feats": 128,
    "stride": 2,
    "dropout": 0.05,
    "learning_rate": 8e-6,
    "batch_size": 32,
    "epochs": 50,
    "scheduler_step_size": 3,
    "scheduler_gamma": 0.33,
    
}

model = train_test(hparams, experiment)

In [ ]:
experiment.end()

# Serialization

In [ ]:
if not os.path.isdir("./models"):
    os.makedirs("./models")

def get_model_paths(experiment_name):
    model_folder_path = f'./models/{experiment_name}'
    model_path = f'{model_folder_path}/{experiment_name}.pth'
    hparams_path = f'{model_folder_path}/{experiment_name}.json'
    return model_folder_path, model_path, hparams_path

## Saving the Model

In [20]:
def save_model(experiment_name):
	model_folder_path, model_path, hparams_path = get_model_paths(experiment_name)

	# create folders if not exist
	if not os.path.isdir(model_folder_path):
		if not os.path.isdir("./models"):
			os.makedirs("./models")
		os.makedirs(model_folder_path)
		
	torch.save(model.state_dict(), model_path)

	with open(hparams_path, 'w') as f:
		json.dump(hparams, f)


In [21]:
save_model(experiment_name)

## Loading the Model

In [73]:
def load_model(experiment_name):
    _, model_path, hparams_path = get_model_paths(experiment_name)
    
    device, _ = get_device()

    with open(hparams_path, 'r') as f:
        hparams = json.load(f)

    model = SpeechRecognitionModel(
        hparams['n_cnn_layers'], hparams['n_rnn_layers'], hparams['rnn_dim'],
        hparams['n_class'], hparams['n_feats'], hparams['stride'], hparams['dropout']
        ).to(device)

    model.load_state_dict(torch.load(model_path))

    return model, hparams

In [74]:
model2, hparams2 = load_model(experiment_name)

# Inference

In [22]:
sample_idx = 100

device, _ = get_device()
spectrogram, label, input_length, label_length = \
    data_processing((test_dataset.__getitem__(n=sample_idx),))
spectrogram, label = spectrogram.to(device), label.to(device)

word_label = text_transform.int_to_text(label.int().tolist()[0])
word_label

'go'

In [23]:
model_inference = model
model_inference.eval()

output = model_inference(spectrogram)
output = F.log_softmax(output, dim=2)

decoded_preds, decoded_targets = GreedyDecoder(output, label, label_length, collapse_repeated=False)

In [27]:
output

tensor([[[-0.5115, -4.7466, -4.5202,  ..., -4.7259, -3.0441, -4.8048],
         [-0.4456, -4.9096, -4.6841,  ..., -4.8948, -3.1459, -4.9505],
         [-0.4307, -4.9666, -4.7123,  ..., -4.9361, -3.1690, -4.9920],
         ...,
         [-0.3824, -5.0876, -4.8416,  ..., -5.0518, -3.2802, -5.1049],
         [-0.4163, -4.9869, -4.7373,  ..., -4.9282, -3.2454, -4.9833],
         [-0.4695, -4.8254, -4.6068,  ..., -4.8005, -3.1809, -4.8367]]],
       device='cuda:0', grad_fn=<LogSoftmaxBackward0>)

In [26]:
print(output.shape)
torch.argmax(output, dim=2)

torch.Size([1, 41, 27])


tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], device='cuda:0')

In [24]:
print(f"Target: {decoded_targets}")
print(f"Prediction: {decoded_preds}")

Target: ['go']
Prediction: ['']
